site_name: SIGAFBA Treinamentos CRM
theme:
  name: material
  language: pt-BR
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - styles.css
extra_javascript:
  - scripts.js
copyright: Copyright© 1999-<span id="copyright-year"></span> SIGAFBA
extra: 
  version: 1.0.0
  generator: false
nav:
  - Introdução: index.md
  - Autenticação:
    - Entrar: routes/autentication/login.md
    - Recuperar Senha: routes/autentication/forgotten_password.md
  - Sistema:
    - Início: routes/settings/home.md
    - Configuração: routes/settings/settings.md
  - Pessoas:
    - Pessoas: routes/people/people.md
    - Aniversariantes: routes/people/birthday.md
  - Negociações: routes/negotiations/negotiations.md
  - Turmas:
    - Turmas: routes/classes/classes.md
    - Participantes: routes/classes/classes_participants.md
    - Links: routes/classes/classes_participants_links.md
    - Novo Link: routes/classes/classes_participants_links_new.md
    - Presença: routes/classes/classes_participants_presence.md
  - Eventos:
    - Calendário: routes/events/events.md
    - Integração Google: routes/events/events_integration.md
  - Financeiro: routes/financial/financial.md
  - Metas: routes/goals/goals.md
  - Tarefas: routes/tasks/tasks.md
  - Dashboard:
    - Dashboard Eventos: routes/dashboard/dashboard_events.md
    - Dashboard Turmas: routes/dashboard/dashboard_classes.md
    - Funil de Vendas: routes/dashboard/sales_funil.md
#   - Financeiro:
#       - v2 (/financeiro/v2): rotas/financeiro_v2.md
#   - Inscrição:
#       - Inscrição por link (/inscricao/:link/:contract/:environment): rotas/inscricao.md
#   - Formulário:
#       - Formulário de pessoa (/formulario/:contract/:environment/:idPerson?/:idPersonForm?): rotas/formulario.md
#   - Turma:
#       - Turma (/turma): rotas/turma.md
#       - Item (/turma/item): rotas/turma_item.md
#       - Lista (/turma/lista): rotas/turma_lista.md
#       - Link Lista (/turma/link/lista): rotas/turma_link_lista.md
#       - Link Registrar (/turma/link/registrar): rotas/turma_link_registrar.md
#       - Link Indicação (/turma/link/indicacao/:contract/:environment/:idClass/:idUser/:idParticipant?): rotas/turma_link_indicacao.md
#   - Pessoas:
#       - Pessoa (/pessoa): rotas/pessoa.md
#       - Lista (/pessoa/lista): rotas/pessoa_lista.md
#       - Aniversariantes (/pessoa/aniversariantes): rotas/pessoa_aniversariantes.md
#       - Registro (/pessoa/registro): rotas/pessoa_registro.md
#       - Metas (/pessoa/metas): rotas/pessoa_metas.md
#   - Classes:
#       - Dashboard (/classes/dashboard): rotas/classes_dashboard.md
#   - Eventos:
#       - Eventos (/pessoa/eventos): rotas/pessoa_eventos.md
#       - Dashboard (/pessoa/eventos/dashboard): rotas/pessoa_eventos_dashboard.md
#   - Negociações:
#       - Negociações (/negociacoes): rotas/negociacoes.md
#       - Funil (/negociacoes/funil): rotas/negociacoes_funil.md
markdown_extensions:
  - toc
  - tables